### ISSUE TITLE
Super-privileged slave

### ISSUE THREAD

**Issue by mancvso** [mesoscloud/mesos#1]
Hi, Why don't you allow the mesos-slave to access the host docker daemon?
As I can see you are running all Mesos jobs inside a container, Is one approach better than the other?

**Comment by pdericson** [comment]
Hi @mancvso I have updated the README.md with a usage example for the slave.  Could you take a look and let me know if it answers your questions?  Much appreciated :)

**Comment by mancvso** [comment]
Yes, it does! Thanks.
(so, it seems just a matter of preference)

**Comment by pdericson** [comment]
Closing this ticket, happy to continue the discussion on mesos-slave if you want :)
